### ISSUE TITLE
Is it possible to run the pipeline on a cohort of 20 trios?

### ISSUE THREAD

**Issue by snijesh** [VCCRI/dv-trio#8]
I have a cohort of 20 trio comprising of 60 sample (20x3=60). If I want use this pipeline should I run the pipeline on each trios (Total 20 run) or are there any option to deal with trio cohort data?

**Comment by eipVCCRI** [comment]
Hi there,

Sorry for the late reply. 

dv-trio will only accept trio, due to the mendelian correction. So in your case it would require 20 runs. We do not envisage expanding it to handle more than three input bams.

Thanks
Eddie
